---
title: "Untitled"
author: "Armand Sutt"
date: '2022-07-03'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

nakatunude_arv <- function(svg,xvg,xdvg,rvg,ck,gnr,alfa,rho){
  probinfgnr <- rep(NA,times=length(svg))
  probinfj <- 1
  for(j in 1:length(svg)){
    probinfgnr[j] <- alfa[,gnr][j]*rho[,gnr][j]*xdvg[j]*(1/(sum(c(svg[j],xvg[j],xdvg[j],rvg[j]))))
    probinfj <- probinfj*((1-alfa[,j][gnr]*rho[,j][gnr]*(1/(sum(c(svg[gnr],xvg[gnr],xdvg[gnr],rvg[gnr])))))^(ck[j]*xdvg[j]))
  }
  p1 <- (1-sum(probinfgnr))**ck[gnr]
  PrB <- 1-probinfj
  PrA <- 1-p1
  PrInf <- min(c(PrA+PrB-PrA*PrB,1))
  return(round(rbinom(1,svg[gnr],PrInf)))
}

vg1<-13312
vg2<-56222
vg3<-71352
vg4<-76913
vg5<-66578
vg6<-62027
vg7<-72479
vg8<-100253
vg9<-98782
vg10=92290
vg11=91346
vg12=87998
vg13=83564
vg14=86534
vg15=79065
vg16=68117
vg17=44781
vg18=36372
xvg1<-0
xvg2<-0
xvg3<-0
xvg4<-0
xvg5<-0
xvg6<-0
xvg7<-10
xvg8<-10
xvg9<-10
xvg10<-0
xvg11<-0
xvg12<-0
xvg13<-0
xvg14<-0
xvg15<-0
xvg16<-0
xvg17<-0
xvg18=0
svg1<-vg1-xvg1
svg2<-vg2-xvg2
svg3<-vg3-xvg3
svg4<-vg4-xvg4
svg5<-vg5-xvg5
svg6<-vg6-xvg6
svg7<-vg7-xvg7
svg8<-vg8-xvg8
svg9<-vg9-xvg9
svg10<-vg10-xvg10
svg11<-vg11-xvg11
svg12<-vg12-xvg12
svg13<-vg13-xvg13
svg14<-vg14-xvg14
svg15<-vg15-xvg15
svg16<-vg16-xvg16
svg17<-vg17-xvg17
svg18=vg18-xvg18
xdvg1<-0
xdvg2<-0
xdvg3<-0
xdvg4<-0
xdvg5<-0
xdvg6<-0
xdvg7<-0
xdvg8<-0
xdvg9<-0
xdvg10<-0
xdvg11<-0
xdvg12<-0
xdvg13<-0
xdvg14<-0
xdvg15<-0
xdvg16<-0
xdvg17<-0
xdvg18=0
rvg1<-0
rvg2<-0
rvg3<-0
rvg4<-0
rvg5<-0
rvg6<-0
rvg7<-10
rvg8<-10
rvg9<-10
rvg10<-0
rvg11<-0
rvg12<-0
rvg13<-0
rvg14<-0
rvg15<-0
rvg16<-0
rvg17<-0
rvg18=0
päev = 0
indeks = 0

alfa = matrix(c(2,0.5,0.5,0.5,0.5,0.5,4,4,0.5,0.5,4,4,0.25,0.25,0.25,0,0,0,
                0.6,5,2,2,0.5,0.5,0.5,0.5,4,4,0.5,0.5,4,4,0.2,0.5,0,0,
                0.2,0.2,10,5,2,0.5,0.5,2,0.5,0.5,2,4,6,3,3,1,0,0,
                0.5,0.2,0.2,10,5,2,0.5,0.5,0.5,0.5,10,5,2,2,1,1,0.5,0.5,
                0,0.5,0.5,2,10,5,2,0.5,0.5,2,2,0.5,0.5,5,10,5,2,2,
                0,0.1,1,2,0.5,5,10,5,5,5,4,4,2,2,1,1,0.5,0,
                4,2,0.5,0.5,0.5,5,10,10,5,5,4,4,3,3,5,4,1,1,
                4,4,2,2,5,10,5,5,4,4,2,2,2,2,1,1,3,1,
                1,1,3,3,1,1,3,3,10,5,4,3,2,2,1,2,3,1,
                0.5,0.5,3,4,0.5,0.5,1,2,4,10,5,4,3,2,1,1,3,3,
                3,3,1,1,2,2,0.5,0.5,4,5,10,10,3,2,1,1,1,1,
                2,2,3,3,0.5,0.5,3,2,1,2,2,10,5,2,1,1,0.5,0.5,
                0.5,3,3,2,0.5,0.5,0.5,0.5,1,1,3,5,10,5,2,1,0,0.5,
                0.5,0.5,3,3,2,0.5,0.5,0.5,0.5,1,1,3,5,10,5,2,1,0.5,
                0.5,0.5,0.5,3,3,2,1,0.5,0.5,0.5,1,1,4,4,12,11,0.5,0.5,
                0.5,0.5,0.5,0.5,2,2,4,4,1,1,5,2,12,12,0.5,12,0.1,0.5,
                0.5,0.5,0.5,0.5,0.5,2,2,1,1,2,4,4,3,3,3,3,15,15,
                0.5,0.5,0.5,0.5,0.5,0.5,2,3,4,1,1,1,1,1,1,1,1,15
                ),nrow=18,byrow=T)

for(i in 1:nrow(alfa)){
  alfa[,i]=alfa[,i]*(1/(sum(alfa[,i])))
}

rho <- rep(NA,18*18)
rho<-matrix(rho,nrow=18)

for(i in 1:18){
  for(j in 1:18){
    rho[i,j]=min(dnorm(j,mean=12,sd=3)+dnorm(j,mean=13,sd=2)+dnorm(i,mean=11,sd=i)+dnorm(j,mean=122,sd=j),1)
  }
}

ck <- c(5,5,5,5,20,20,15,3,5,5,3,3,2,2,2,2,2,2)
sumhowmany=0
indeks=0
päev=0
dfg2 <- data.frame(päev,svg1,svg2,svg3,svg4,svg5,svg6,svg7,svg8,svg9,svg10,svg11,
                  svg12,svg13,svg14,svg15,svg16,svg17,svg18,
                  xvg1,xvg2,xvg3,xvg4,xvg5,xvg6,xvg7,xvg8,xvg9,
                  xvg10,xvg11,xvg12,xvg13,xvg14,xvg15,xvg16,xvg17,xvg18,
                  xdvg1,xdvg2,xdvg3,xdvg4,xdvg5,xdvg6,xdvg7,xdvg8,xdvg9,
                  xdvg10,xdvg11,xdvg12,xdvg13,xdvg14,xdvg15,xdvg16,xdvg17,xdvg18,
                  rvg1,rvg2,rvg3,rvg4,rvg5,rvg6,rvg7,rvg8,rvg9,rvg10,
                  rvg11,rvg12,rvg13,rvg14,rvg15,rvg16,rvg17,rvg18,indeks,sumhowmany)
dfg2 <- dfg2[-1,]

for(i in 1:300){
# #rho = c(0.02,0.1,0.2)
  ti=1
  vg1<-13312
  vg2<-56222
  vg3<-71352
  vg4<-76913
  vg5<-66578
  vg6<-62027
  vg7<-72479
  vg8<-100253
  vg9<-98782
  vg10=92290
  vg11=91346
  vg12=87998
  vg13=83564
  vg14=86534
  vg15=79065
  vg16=68117
  vg17=44781
  vg18=36372
  xvg1<-0
  xvg2<-0
  xvg3<-0
  xvg4<-0
  xvg5<-0
  xvg6<-0
  xvg7<-10
  xvg8<-10
  xvg9<-10
  xvg10<-0
  xvg11<-0
  xvg12<-0
  xvg13<-0
  xvg14<-0
  xvg15<-0
  xvg16<-0
  xvg17<-0
  xvg18=0
  svg1<-vg1-xvg1
  svg2<-vg2-xvg2
  svg3<-vg3-xvg3
  svg4<-vg4-xvg4
  svg5<-vg5-xvg5
  svg6<-vg6-xvg6
  svg7<-vg7-xvg7
  svg8<-vg8-xvg8
  svg9<-vg9-xvg9
  svg10<-vg10-xvg10
  svg11<-vg11-xvg11
  svg12<-vg12-xvg12
  svg13<-vg13-xvg13
  svg14<-vg14-xvg14
  svg15<-vg15-xvg15
  svg16<-vg16-xvg16
  svg17<-vg17-xvg17
  svg18=vg18-xvg18
  xdvg1<-0
  xdvg2<-0
  xdvg3<-0
  xdvg4<-0
  xdvg5<-0
  xdvg6<-0
  xdvg7<-0
  xdvg8<-0
  xdvg9<-0
  xdvg10<-0
  xdvg11<-0
  xdvg12<-0
  xdvg13<-0
  xdvg14<-0
  xdvg15<-0
  xdvg16<-0
  xdvg17<-0
  xdvg18=0
  rvg1<-0
  rvg2<-0
  rvg3<-0
  rvg4<-0
  rvg5<-0
  rvg6<-0
  rvg7<-10
  rvg8<-10
  rvg9<-10
  rvg10<-0
  rvg11<-0
  rvg12<-0
  rvg13<-0
  rvg14<-0
  rvg15<-0
  rvg16<-0
  rvg17<-0
  rvg18=0
  #c=2
  Tx1 = 5
  Tx2 = 2
  #rho=0.3

  number_added = 0
  number_taken = 0
  world <- c(svg1,svg2,svg3,svg4,svg5,svg6,svg7,svg8,svg9,svg10,svg11,svg12,
             svg13,svg14,svg15,svg16,svg17,svg18,
              xvg1,xvg2,xvg3,xvg4,xvg5,xvg6,xvg7,xvg8,xvg9,xvg10,xvg11,xvg12,
             xvg13,xvg14,xvg15,xvg16,xvg17,xvg18,
              xdvg1,xdvg2,xdvg3,xdvg4,xdvg5,xdvg6,xdvg7,xdvg8,xdvg9,xdvg10,
             xdvg11,xdvg12,xdvg13,xdvg14,xdvg15,xdvg16,xdvg17,xdvg18,
              rvg1,rvg2,rvg3,rvg4,rvg5,rvg6,rvg7,rvg8,rvg9,rvg10,rvg11,
             rvg12,rvg13,rvg14,rvg15,rvg16,rvg17,rvg18)
  n=sum(world)
  indeks = i
  päev=0
  päev=0
  plum = T
  sumhowmany=0
  how_set<-data.frame(xvg1,xvg2,xvg3,xvg4,xvg5,xvg6,xvg7,xvg8,xvg9,xvg10,xvg11,xvg12,
             xvg13,xvg14,xvg15,xvg16,xvg17,xvg18)
  päev = 0
  väärtused <- c(päev,svg1,svg2,svg3,svg4,svg5,svg6,svg7,svg8,svg9,svg10,svg11,svg12,
             svg13,svg14,svg15,svg16,svg17,svg18,
              xvg1,xvg2,xvg3,xvg4,xvg5,xvg6,xvg7,xvg8,xvg9,xvg10,xvg11,xvg12,
             xvg13,xvg14,xvg15,xvg16,xvg17,xvg18,
              xdvg1,xdvg2,xdvg3,xdvg4,xdvg5,xdvg6,xdvg7,xdvg8,xdvg9,xdvg10,
             xdvg11,xdvg12,xdvg13,xdvg14,xdvg15,xdvg16,xdvg17,xdvg18,
              rvg1,rvg2,rvg3,rvg4,rvg5,rvg6,rvg7,rvg8,rvg9,rvg10,rvg11,
             rvg12,rvg13,rvg14,rvg15,rvg16,rvg17,rvg18,indeks,sumhowmany)
  dfg2[nrow(dfg2)+1,]=väärtused
  if(i%%20==0){
    print(i)
  }
  while(plum){
    svg <- as.numeric(world[1:18])
    xvg <- as.numeric(world[19:36])
    xdvg <- as.numeric(world[37:54])
    rvg <-as.numeric(world[55:72])
    how_many_added <- rep(NA,length(svg))
    for(j in 1:length(svg)){
      how_many_added[j]=ifelse(nakatunude_arv(svg,xvg,xdvg,rvg,ck,j,alfa,rho)<svg[j],nakatunude_arv(svg,xvg,xdvg,rvg,ck,j,alfa,rho),svg[j])
    }
    sumhowmany <- sum(how_many_added)
    päev=päev + 1
    how_set[nrow(how_set)+1,] <- how_many_added
    if(sum(c(world[1:18],world[55:72]))==n){
      plum = F
      #print(paste("päev",päev))
      #print(c("S ", "X ", "R "))
      #print(world)
    }
    else{
      #print(paste("päev",päev))
      #print(c("S ", "X ", "R "))
      #print(world)
      world[19:36] = world[19:36]+how_many_added
      world[1:18] = world[1:18]-how_many_added
      if((Tx1-Tx2)<ti){
        #number_taken <- how_set[ti-Tx2+1,]
        world[19:36] = world[19:36]-as.numeric(how_set[ti-(Tx1-Tx2),])
        world[37:54] = world[37:54]+as.numeric(how_set[ti-(Tx1-Tx2),])
        if(Tx1<ti){
          world[37:54] = world[37:54]-as.numeric(how_set[ti-Tx1,])
          world[55:72] = world[55:72]+as.numeric(how_set[ti-Tx1,])
        }
      }
      ti = ti + 1
      #number_added <- how_many_added
      väärtused <- c(päev,world,indeks,sumhowmany)
      dfg2[nrow(dfg2)+1,]=väärtused
    }
  }
}

dfg2$xvg1. = dfg2$xvg1+dfg2$xdvg1
dfg2$xvg2. = dfg2$xvg2+dfg2$xdvg2
dfg2$xvg3. = dfg2$xvg3+dfg2$xdvg3
dfg2$xvg4. = dfg2$xvg4+dfg2$xdvg4
dfg2$xvg5. = dfg2$xvg5+dfg2$xdvg5
dfg2$xvg6. = dfg2$xvg6+dfg2$xdvg6
dfg2$xvg7. = dfg2$xvg7+dfg2$xdvg7
dfg2$xvg8. = dfg2$xvg8+dfg2$xdvg8
dfg2$xvg9. = dfg2$xvg9+dfg2$xdvg9
dfg2$xvg10. = dfg2$xvg10+dfg2$xdvg10
dfg2$xvg11. = dfg2$xvg11+dfg2$xdvg11
dfg2$xvg12. = dfg2$xvg12+dfg2$xdvg12
dfg2$xvg13. = dfg2$xvg13+dfg2$xdvg13
dfg2$xvg14. = dfg2$xvg14+dfg2$xdvg14
dfg2$xvg15. = dfg2$xvg15+dfg2$xdvg15
dfg2$xvg16. = dfg2$xvg16+dfg2$xdvg16
dfg2$xvg17. = dfg2$xvg17+dfg2$xdvg17
dfg2$xvg18. = dfg2$xvg18+dfg2$xdvg18

dfg2$xvg <- NA

for(i in 1:nrow(dfg2)){
  dfg2$xvg[i]<-sum(dfg2[i,76:93])
  if(i%%2500==0){
  print(i)
  }
}

library("ggplot2")

library("reshape2")

dfg2$how_many_added <- 0

dfg2$xvgnoninf <- NA 

for(i in 1:nrow(dfg2)){
  dfg2$xvgnoninf[i]=sum(dfg2[i,20:37])
  if(i%%10000==0){
    print(i)
  }
}

dfg2$svg<-NA

for(i in 1:nrow(dfg2)){
  dfg2$svg[i]=sum(dfg2[i,2:19])
}

dfg2$rvg =NA

for(i in 1:nrow(dfg2)){
  dfg2$rvg[i]=sum(dfg2[i,56:73])
}


#a <- with(df, tapply(value,päev,mean))

df <- melt(dfg2[,1:19], id.vars = 'päev', variable.name = 'grupid')

dfsvg <- aggregate(value ~ grupid + päev, data = df, FUN= "mean" )

ggplot(dfsvg, aes(päev, value))+
  geom_line(aes(color=grupid))
  


df <- melt(dfg2[,c(1,76:93)],id.vars = 'päev', variable.name = 'grupid')

dfxvg <- aggregate(value ~ grupid + päev, data = df, FUN= "mean" )

ggplot(dfxvg, aes(päev, value))+
  geom_line(aes(color=grupid))

df <- melt(dfg2[,c(1,56:73)],id.vars = 'päev', variable.name = 'grupid')

dfrvg <- aggregate(value ~ grupid + päev, data = df, FUN= "mean" )

ggplot(dfrvg, aes(päev, value))+
  geom_line(aes(color=grupid))

dfsvg <- melt(dfg2[,c(1,97)],id.vars='päev',variable.name='grupid')

dfsvgmean <- aggregate(value ~ grupid + päev, data = dfsvg, FUN="median")
dfsvgsd <- aggregate(value ~ grupid + päev, data = dfsvg, FUN = "sd")

```
```{r}

alfa = matrix(c(2,0.5,0.5,0.5,0.5,0.5,4,4,0.5,0.5,4,4,0.25,0.25,0.25,0,0,0,
                0.6,5,2,2,0.5,0.5,0.5,0.5,4,4,0.5,0.5,4,4,0.2,0.5,0,0,
                0.2,0.2,10,5,2,0.5,0.5,2,0.5,0.5,2,4,6,3,3,1,0,0,
                0.5,0.2,0.2,10,5,2,0.5,0.5,0.5,0.5,10,5,2,2,1,1,0.5,0.5,
                0,0.5,0.5,2,10,5,2,0.5,0.5,2,2,0.5,0.5,5,10,5,2,2,
                0,0.1,1,2,0.5,5,10,5,5,5,4,4,2,2,1,1,0.5,0,
                4,2,0.5,0.5,0.5,5,10,10,5,5,4,4,3,3,5,4,1,1,
                4,4,2,2,5,10,5,5,4,4,2,2,2,2,1,1,3,1,
                1,1,3,3,1,1,3,3,10,5,4,3,2,2,1,2,3,1,
                0.5,0.5,3,4,0.5,0.5,1,2,4,10,5,4,3,2,1,1,3,3,
                3,3,1,1,2,2,0.5,0.5,4,5,10,10,3,2,1,1,1,1,
                2,2,3,3,0.5,0.5,3,2,1,2,2,10,5,2,1,1,0.5,0.5,
                0.5,3,3,2,0.5,0.5,0.5,0.5,1,1,3,5,10,5,2,1,0,0.5,
                0.5,0.5,3,3,2,0.5,0.5,0.5,0.5,1,1,3,5,10,5,2,1,0.5,
                0.5,0.5,0.5,3,3,2,1,0.5,0.5,0.5,1,1,4,4,12,11,0.5,0.5,
                0.5,0.5,0.5,0.5,2,2,4,4,1,1,5,2,12,12,0.5,12,0.1,0.5,
                0.5,0.5,0.5,0.5,0.5,2,2,1,1,2,4,4,3,3,3,3,15,15,
                0.5,0.5,0.5,0.5,0.5,0.5,2,3,4,1,1,1,1,1,1,1,1,15
                ),nrow=18,byrow=T)

for(i in 1:nrow(alfa)){
  alfa[,i]=alfa[,i]*(1/(sum(alfa[,i])))
}

alfa[c(2,3,4),]=alfa[c(2,3,4),]*0.01

indeks=0
päev=0
sumhowmany=0

ck <- c(5,50,50,50,20,20,15,3,5,5,3,3,2,2,2,2,2,2)

dfg3 <- data.frame(päev,svg1,svg2,svg3,svg4,svg5,svg6,svg7,svg8,svg9,svg10,svg11,
                  svg12,svg13,svg14,svg15,svg16,svg17,svg18,
                  xvg1,xvg2,xvg3,xvg4,xvg5,xvg6,xvg7,xvg8,xvg9,
                  xvg10,xvg11,xvg12,xvg13,xvg14,xvg15,xvg16,xvg17,xvg18,
                  xdvg1,xdvg2,xdvg3,xdvg4,xdvg5,xdvg6,xdvg7,xdvg8,xdvg9,
                  xdvg10,xdvg11,xdvg12,xdvg13,xdvg14,xdvg15,xdvg16,xdvg17,xdvg18,
                  rvg1,rvg2,rvg3,rvg4,rvg5,rvg6,rvg7,rvg8,rvg9,rvg10,
                  rvg11,rvg12,rvg13,rvg14,rvg15,rvg16,rvg17,rvg18,indeks,sumhowmany=0)
dfg3 <- dfg3[-1,]

for(i in 1:300){
# #rho = c(0.02,0.1,0.2)
  ti=1
  vg1<-13312
  vg2<-56222
  vg3<-71352
  vg4<-76913
  vg5<-66578
  vg6<-62027
  vg7<-72479
  vg8<-100253
  vg9<-98782
  vg10=92290
  vg11=91346
  vg12=87998
  vg13=83564
  vg14=86534
  vg15=79065
  vg16=68117
  vg17=44781
  vg18=36372
  xvg1<-0
  xvg2<-0
  xvg3<-0
  xvg4<-0
  xvg5<-0
  xvg6<-0
  xvg7<-10
  xvg8<-10
  xvg9<-10
  xvg10<-0
  xvg11<-0
  xvg12<-0
  xvg13<-0
  xvg14<-0
  xvg15<-0
  xvg16<-0
  xvg17<-0
  xvg18=0
  svg1<-vg1-xvg1
  svg2<-vg2-xvg2
  svg3<-vg3-xvg3
  svg4<-vg4-xvg4
  svg5<-vg5-xvg5
  svg6<-vg6-xvg6
  svg7<-vg7-xvg7
  svg8<-vg8-xvg8
  svg9<-vg9-xvg9
  svg10<-vg10-xvg10
  svg11<-vg11-xvg11
  svg12<-vg12-xvg12
  svg13<-vg13-xvg13
  svg14<-vg14-xvg14
  svg15<-vg15-xvg15
  svg16<-vg16-xvg16
  svg17<-vg17-xvg17
  svg18=vg18-xvg18
  xdvg1<-0
  xdvg2<-0
  xdvg3<-0
  xdvg4<-0
  xdvg5<-0
  xdvg6<-0
  xdvg7<-0
  xdvg8<-0
  xdvg9<-0
  xdvg10<-0
  xdvg11<-0
  xdvg12<-0
  xdvg13<-0
  xdvg14<-0
  xdvg15<-0
  xdvg16<-0
  xdvg17<-0
  xdvg18=0
  rvg1<-0
  rvg2<-0
  rvg3<-0
  rvg4<-0
  rvg5<-0
  rvg6<-0
  rvg7<-10
  rvg8<-10
  rvg9<-10
  rvg10<-0
  rvg11<-0
  rvg12<-0
  rvg13<-0
  rvg14<-0
  rvg15<-0
  rvg16<-0
  rvg17<-0
  rvg18=0
  #c=2
  Tx1 = 5
  Tx2 = 3
  #rho=0.3

  number_added = 0
  number_taken = 0
  world <- c(svg1,svg2,svg3,svg4,svg5,svg6,svg7,svg8,svg9,svg10,svg11,svg12,
             svg13,svg14,svg15,svg16,svg17,svg18,
              xvg1,xvg2,xvg3,xvg4,xvg5,xvg6,xvg7,xvg8,xvg9,xvg10,xvg11,xvg12,
             xvg13,xvg14,xvg15,xvg16,xvg17,xvg18,
              xdvg1,xdvg2,xdvg3,xdvg4,xdvg5,xdvg6,xdvg7,xdvg8,xdvg9,xdvg10,
             xdvg11,xdvg12,xdvg13,xdvg14,xdvg15,xdvg16,xdvg17,xdvg18,
              rvg1,rvg2,rvg3,rvg4,rvg5,rvg6,rvg7,rvg8,rvg9,rvg10,rvg11,
             rvg12,rvg13,rvg14,rvg15,rvg16,rvg17,rvg18)
  n=sum(world)
  indeks = i
  päev=0
  päev=0
  plum = T
  how_set<-data.frame(xvg1,xvg2,xvg3,xvg4,xvg5,xvg6,xvg7,xvg8,xvg9,xvg10,xvg11,xvg12,
             xvg13,xvg14,xvg15,xvg16,xvg17,xvg18)
  päev = 0
  väärtused <- c(päev,svg1,svg2,svg3,svg4,svg5,svg6,svg7,svg8,svg9,svg10,svg11,svg12,
             svg13,svg14,svg15,svg16,svg17,svg18,
              xvg1,xvg2,xvg3,xvg4,xvg5,xvg6,xvg7,xvg8,xvg9,xvg10,xvg11,xvg12,
             xvg13,xvg14,xvg15,xvg16,xvg17,xvg18,
              xdvg1,xdvg2,xdvg3,xdvg4,xdvg5,xdvg6,xdvg7,xdvg8,xdvg9,xdvg10,
             xdvg11,xdvg12,xdvg13,xdvg14,xdvg15,xdvg16,xdvg17,xdvg18,
              rvg1,rvg2,rvg3,rvg4,rvg5,rvg6,rvg7,rvg8,rvg9,rvg10,rvg11,
             rvg12,rvg13,rvg14,rvg15,rvg16,rvg17,rvg18,indeks,sumhowmany)
  dfg3[nrow(dfg3)+1,]=väärtused
  if(i%%50==0){
    print(i)
  }
  while(plum){
    svg <- as.numeric(world[1:18])
    xvg <- as.numeric(world[19:36])
    xdvg <- as.numeric(world[37:54])
    rvg <-as.numeric(world[55:72])
    how_many_added <- rep(NA,length(svg))
    for(j in 1:length(svg)){
      how_many_added[j]=ifelse(nakatunude_arv(svg,xvg,xdvg,rvg,ck,j,alfa,rho)<svg[j],nakatunude_arv(svg,xvg,xdvg,rvg,ck,j,alfa,rho),svg[j])
    }
    sumhowmany = sum(how_many_added)
    päev=päev + 1
    how_set[nrow(how_set)+1,] <- how_many_added
    if(sum(c(world[1:18],world[55:72]))==n){
      plum = F
      #print(paste("päev",päev))
      #print(c("S ", "X ", "R "))
      #print(world)
    }
    else{
      #print(paste("päev",päev))
      #print(c("S ", "X ", "R "))
      #print(world)
      world[19:36] = world[19:36]+how_many_added
      world[1:18] = world[1:18]-how_many_added
      if((Tx1-Tx2)<ti){
        #number_taken <- how_set[ti-Tx2+1,]
        world[19:36] = world[19:36]-as.numeric(how_set[ti-(Tx1-Tx2),])
        world[37:54] = world[37:54]+as.numeric(how_set[ti-(Tx1-Tx2),])
        if(Tx1<ti){
          world[37:54] = world[37:54]-as.numeric(how_set[ti-Tx1,])
          world[55:72] = world[55:72]+as.numeric(how_set[ti-Tx1,])
        }
      }
      ti = ti + 1
      #number_added <- how_many_added
      väärtused <- c(päev,world,indeks,sumhowmany)
      dfg3[nrow(dfg3)+1,]=väärtused
    }
  }
}

dfg3$xvg1. = dfg3$xvg1+dfg3$xdvg1
dfg3$xvg2. = dfg3$xvg2+dfg3$xdvg2
dfg3$xvg3. = dfg3$xvg3+dfg3$xdvg3
dfg3$xvg4. = dfg3$xvg4+dfg3$xdvg4
dfg3$xvg5. = dfg3$xvg5+dfg3$xdvg5
dfg3$xvg6. = dfg3$xvg6+dfg3$xdvg6
dfg3$xvg7. = dfg3$xvg7+dfg3$xdvg7
dfg3$xvg8. = dfg3$xvg8+dfg3$xdvg8
dfg3$xvg9. = dfg3$xvg9+dfg3$xdvg9
dfg3$xvg10. = dfg3$xvg10+dfg3$xdvg10
dfg3$xvg11. = dfg3$xvg11+dfg3$xdvg11
dfg3$xvg12. = dfg3$xvg12+dfg3$xdvg12
dfg3$xvg13. = dfg3$xvg13+dfg3$xdvg13
dfg3$xvg14. = dfg3$xvg14+dfg3$xdvg14
dfg3$xvg15. = dfg3$xvg15+dfg3$xdvg15
dfg3$xvg16. = dfg3$xvg16+dfg3$xdvg16
dfg3$xvg17. = dfg3$xvg17+dfg3$xdvg17
dfg3$xvg18. = dfg3$xvg18+dfg3$xdvg18

dfg3$xvg <- NA

for(i in 1:nrow(dfg3)){
  dfg3$xvg[i]<-sum(dfg3[i,76:93])
  if(i%%2500==0){
  print(i)
  }
}

library("ggplot2")

library("reshape2")

dfg3$how_many_added <- 0

dfg3$xvgnoninf <- NA 

for(i in 1:nrow(dfg3)){
  dfg3$xvgnoninf[i]=sum(dfg3[i,20:37])
  if(i%%10000==0){
    print(i)
  }
}

dfg3$svg<-NA

for(i in 1:nrow(dfg3)){
  dfg3$svg[i]=sum(dfg3[i,2:19])
}

dfg3$rvg =NA

for(i in 1:nrow(dfg3)){
  dfg3$rvg[i]=sum(dfg3[i,56:73])
}


#a <- with(df, tapply(value,päev,mean))

df <- melt(dfg3[,1:19], id.vars = 'päev', variable.name = 'grupid')

dfsvg <- aggregate(value ~ grupid + päev, data = df, FUN= "mean" )

ggplot(dfsvg, aes(päev, value))+
  geom_line(aes(color=grupid))+
  xlim(0,65)
  


df <- melt(dfg3[,c(1,76:93)],id.vars = 'päev', variable.name = 'grupid')

dfxvg <- aggregate(value ~ grupid + päev, data = df, FUN= "mean" )

ggplot(dfxvg, aes(päev, value))+
  geom_line(aes(color=grupid))+
  xlim(0,65)

df <- melt(dfg3[,c(1,56:73)],id.vars = 'päev', variable.name = 'grupid')

dfrvg <- aggregate(value ~ grupid + päev, data = df, FUN= "mean" )

ggplot(dfrvg, aes(päev, value))+
  geom_line(aes(color=grupid))+
  xlim(0,65)

ESn <- c()

EXn <- c()

ERn <- c()

sSn <- c()

sXn <- c()

sRn <- c()

qSnu <- c()

qXnu <- c()

qRnu <- c()

qSnl <- c()

qXnl <- c()

qRnl <- c()

for(i in 1:length(unique(dfg2$päev))){
  ESn <- c(ESn, mean(dfg2$svg[dfg2$päev==unique(dfg2$päev)[i]]))
  EXn <- c(EXn, mean(dfg2$xvg[dfg2$päev==unique(dfg2$päev)[i]]))
  ERn <- c(ERn, mean(dfg2$xvg[dfg2$päev==unique(dfg2$päev)[i]]))
  sSn <- c(sSn, sd(dfg2$svg[dfg2$päev==unique(dfg2$päev)[i]]))
  sXn <- c(sXn, sd(dfg2$xvg[dfg2$päev==unique(dfg2$päev)[i]]))
  sRn <- c(sRn, sd(dfg2$rvg[dfg2$päev==unique(dfg2$päev)[i]]))
  qSnu <- c(qSnu, mean(dfg2$svg[dfg2$päev==unique(dfg2$päev)[i]])+1.645*sd(dfg2$svg[dfg2$päev==unique(dfg2$päev)[i]]))
  qXnu <- c(qXnu, mean(dfg2$xvg[dfg2$päev==unique(dfg2$päev)[i]])+1.645*sd(dfg2$xvg[dfg2$päev==unique(dfg2$päev)[i]]))
  qRnu <- c(qRnu, mean(dfg2$rvg[dfg2$päev==unique(dfg2$päev)[i]])+1.645*sd(dfg2$rvg[dfg2$päev==unique(dfg2$päev)[i]]))
  qSnl <- c(qSnl, mean(dfg2$svg[dfg2$päev==unique(dfg2$päev)[i]])-1.645*sd(dfg2$svg[dfg2$päev==unique(dfg2$päev)[i]]))
  qXnl <- c(qXnl, mean(dfg2$xvg[dfg2$päev==unique(dfg2$päev)[i]])-1.645*sd(dfg2$xvg[dfg2$päev==unique(dfg2$päev)[i]]))
  qRnl <- c(qRnl, mean(dfg2$rvg[dfg2$päev==unique(dfg2$päev)[i]])-1.645*sd(dfg2$rvg[dfg2$päev==unique(dfg2$päev)[i]]))
  print(i)
}

tulem <- round(data.frame(päev=unique(dfg2$päev),EXn, sXn, qXnu, qXnl))

kESn <- c()

kEXn <- c()

kERn <- c()

ksSn <- c()

ksXn <- c()

ksRn <- c()

kqSnu <- c()

kqXnu <- c()

kqRnu <- c()

kqSnl <- c()

kqXnl <- c()

kqRnl <- c()

for(i in 1:length(unique(dfg3$päev))){
  kESn <- c(kESn, mean(dfg3$svg[dfg3$päev==unique(dfg3$päev)[i]]))
  kEXn <- c(kEXn, mean(dfg3$xvg[dfg3$päev==unique(dfg3$päev)[i]]))
  kERn <- c(kERn, mean(dfg3$xvg[dfg3$päev==unique(dfg3$päev)[i]]))
  ksSn <- c(ksSn, sd(dfg3$svg[dfg3$päev==unique(dfg3$päev)[i]]))
  ksXn <- c(ksXn, sd(dfg3$xvg[dfg3$päev==unique(dfg3$päev)[i]]))
  ksRn <- c(ksRn, sd(dfg3$rvg[dfg3$päev==unique(dfg3$päev)[i]]))
  kqSnu <- c(kqSnu, mean(dfg3$svg[dfg3$päev==unique(dfg3$päev)[i]])+1.645*sd(dfg3$svg[dfg3$päev==unique(dfg3$päev)[i]]))
  kqXnu <- c(kqXnu, mean(dfg3$xvg[dfg3$päev==unique(dfg3$päev)[i]])+1.645*sd(dfg3$xvg[dfg3$päev==unique(dfg3$päev)[i]]))
  kqRnu <- c(kqRnu, mean(dfg3$rvg[dfg3$päev==unique(dfg3$päev)[i]])+1.645*sd(dfg3$rvg[dfg3$päev==unique(dfg3$päev)[i]]))
  kqSnl <- c(kqSnl, mean(dfg3$svg[dfg3$päev==unique(dfg3$päev)[i]])-1.645*sd(dfg3$svg[dfg3$päev==unique(dfg3$päev)[i]]))
  kqXnl <- c(kqXnl, mean(dfg3$xvg[dfg3$päev==unique(dfg3$päev)[i]])-1.645*sd(dfg3$xvg[dfg3$päev==unique(dfg3$päev)[i]]))
  kqRnl <- c(kqRnl, mean(dfg3$rvg[dfg3$päev==unique(dfg3$päev)[i]])-1.645*sd(dfg3$rvg[dfg3$päev==unique(dfg3$päev)[i]]))
  print(i)
}

tulem2 <- round(data.frame(päev=unique(dfg3$päev),kEXn, ksXn, kqXnu, kqXnl))
library(dplyr)
tulem3 <- left_join(tulem,tulem2,by="päev")

```