---
title: "SIR SAAREMAA"
author: "Armand Sutt"
date: '2022-06-21'
output: 
  pdf_document: 
    keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#sõltumatu mudel
# p_of_inf <- function(n,x1,x2,c1,c2,rho1,rho2){
#   tehe1 = (1-(1-(x1/n)*rho1)^c1)
#   tehe2 = (1-(1-rho2/n)^(c2*x2))
#   tehe3 <- tehe1 + tehe2 - tehe1*tehe2
#   return(tehe3)
# }
# 
# p_of_inf2 <- function(n1,x1,x2,c1,c2,rho1,rho2){
#   tehe1 = rho1*c1*x1/n1
#   tehe2 = rho2*x2*c2/n1
#   tehe3 <- tehe1 + tehe2 - tehe1*tehe2
#   return(max(c(tehe3,1)))
# }
# 
# # p_of_inf <- function(n,x1,x2,c1,c2,rho1,rho2){
# #   tehe1 = x1/n
# #   tehe2 = (1-(1-rho2/n)^(x2))
# #   tehe3 <- tehe1 + tehe2 - tehe1*tehe2
# #   return(tehe3)
# # }
# 
# #kumulatiivne mudel
# # p_of_inf <- function(n,x1,x2,c1,c2,rho){
# # tehe1 <- c1*x1/n
# # tehe2 <- c2*x2/n
# # tehe3 <- tehe1+tehe2
# # tehe4 <- rho*tehe3
# # return(tehe4)
# # }
# #sõltumatu mudel
# nakatunude_arv <- function(svg,xvg,xdvg,rvg,ck,gnr,alfa,rho){
#   alfamat<-matrix(alfa,ncol=length(svg),byrow=T)
#   huvipakkuvad_kordajad1 <- alfamat[gnr,1:nrow(alfamat)]
#   huvipakkuvad_kordajad2 <- alfamat[1:nrow(alfamat),gnr]
#   rhou <- rho[gnr,]
#   rhov <- rho[,gnr]
#   skaleeritudsvg1 <- huvipakkuvad_kordajad1*svg
#   skaleeritudsvg2 <- huvipakkuvad_kordajad2*svg
#   skaleeritudxvg1 <- huvipakkuvad_kordajad1*xvg
#   skaleeritudxvg2 <- huvipakkuvad_kordajad2*xvg
#   skaleeritudxdvg1 <- huvipakkuvad_kordajad1*xdvg
#   skaleeritudxdvg2 <- huvipakkuvad_kordajad2*xdvg
#   skaleeritudrvg1 <- huvipakkuvad_kordajad1*rvg
#   skaleeritudrvg2 <- huvipakkuvad_kordajad2*rvg
#   n1 <- sum(c(skaleeritudsvg1,skaleeritudxvg1,skaleeritudxdvg1,skaleeritudrvg1))
#   n2 <- sum(c(skaleeritudsvg2,skaleeritudxvg2,skaleeritudxdvg2,skaleeritudrvg2))
#   n <- sum(c(svg,xvg,xdvg,rvg))
#   skal1 <- n/n1
#   skal2 <- n/n2
#   newxvg1 <- round(skaleeritudxdvg1*skal1)
#   newxvg2 <- round(skaleeritudxdvg2*skal2)
#   c1 <- ck[gnr]
#   pinf <- rep(NA,nrow(alfamat))
#   for(i in 1:nrow(alfamat)){
#     rho1<-rhou[gnr]
#     rho2<-rhov[i]
#     pinf[i] <- p_of_inf(n,newxvg1[gnr],newxvg2[i],c1,ck[i],rho1,rho2)
#   }
# #pnotinf <- 1
#   pnotinf <- prod(1-pinf)**c1
# #pnotinfc <- pnotinf**c
#   pinfc <- 1-pnotinf
#   nofinf <- rbinom(1,round(svg[gnr]),pinfc)
#   return(nofinf)
# }
# 
# nakatunude_arv2 <- function(svg,xvg,xdvg,rvg,ck,gnr,alfa,rho){
#   alfamat<-matrix(alfa,ncol=length(svg),byrow=T)
#   huvipakkuvad_kordajad1 <- alfamat[gnr,1:nrow(alfamat)]
#   huvipakkuvad_kordajad2 <- alfamat[1:nrow(alfamat),gnr]
#   rhou <- rho[gnr,]
#   rhov <- rho[,gnr]
#   skaleeritudsvg1 <- huvipakkuvad_kordajad1*svg
#   skaleeritudsvg2 <- huvipakkuvad_kordajad2*svg
#   skaleeritudxvg1 <- huvipakkuvad_kordajad1*xvg
#   skaleeritudxvg2 <- huvipakkuvad_kordajad2*xvg
#   skaleeritudxdvg1 <- huvipakkuvad_kordajad1*xdvg
#   skaleeritudxdvg2 <- huvipakkuvad_kordajad2*xdvg
#   skaleeritudrvg1 <- huvipakkuvad_kordajad1*rvg
#   skaleeritudrvg2 <- huvipakkuvad_kordajad2*rvg
#   n1 <- sum(c(skaleeritudsvg1,skaleeritudxvg1,skaleeritudxdvg1,skaleeritudrvg1))
#   n2 <- sum(c(skaleeritudsvg2,skaleeritudxvg2,skaleeritudxdvg2,skaleeritudrvg2))
#   n <- sum(c(svg,xvg,xdvg,rvg))
#   skal1 <- n/n1
#   skal2 <- n/n2
#   newxvg1 <- round(skaleeritudxdvg1*skal1)
#   newxvg2 <- round(skaleeritudxdvg2*skal2)
#   c1 <- ck[gnr]
#   pinf <- rep(NA,nrow(alfamat))
#   for(i in 1:nrow(alfamat)){
#     rho1<-rhou[gnr]
#     rho2<-rhov[i]
#     pinf[i] <- p_of_inf2(n,newxvg1[gnr],newxvg2[i],c1,ck[i],rho1,rho2)
#   }
# #pnotinf <- 1
#   pnotinf <- prod(1-pinf)**c1
# #pnotinfc <- pnotinf**c
#   pinfc <- 1-pnotinf
#   nofinf <- rbinom(1,svg[gnr],pinfc)
#   return(nofinf)
# }
# 
# probcalc <- function(gnrxdvg,jxdvg,gnr,jn,ckgnr,ckj,alfagnrj,rhognrj,alfaj,rhoj){
#   
# }

nakatunude_arv <- function(svg,xvg,xdvg,rvg,ck,gnr,alfa,rho){
  probinfgnr <- rep(NA,times=length(svg))
  probinfj <- 1
  for(j in 1:length(svg)){
    probinfgnr[j] <- alfa[,gnr][j]*rho[,gnr][j]*xdvg[j]*(1/(sum(c(svg[j],xvg[j],xdvg[j],rvg[j]))))
    probinfj <- probinfj*((1-alfa[,j][gnr]*rho[,j][gnr]*(1/(sum(c(svg[gnr],xvg[gnr],xdvg[gnr],rvg[gnr])))))^(ck[j]*xdvg[j]))
  }
  p1 <- (1-sum(probinfgnr))**ck[gnr]
  PrB <- 1-probinfj
  PrA <- 1-p1
  PrInf <- min(c(PrA+PrB-PrA*PrB,1))
  return(round(rbinom(1,svg[gnr],PrInf)))
}

nakatunude_arv2 <- function(svg,xvg,xdvg,rvg,ck,gnr,alfa,rho){
  PrA <- 0
  PrB <- 0
  for(j in 1:length(svg)){
    PrA = PrA + ck[gnr]*alfa[,gnr][j]*xdvg[j]*rho[,gnr][j]*1/(sum(c(svg[j],xvg[j],xdvg[j],rvg[j])))
    PrB = PrB + ck[j]*alfa[,j][gnr]*xdvg[gnr]*rho[,j][gnr]*1/(sum(c(svg[gnr],xvg[gnr],xdvg[gnr],rvg[gnr])))
  }
  PrInf <- min(c(PrA+PrB,1))
  return(rbinom(1,svg[gnr],PrInf))
}

vg1<-1511 #0-4
vg2<-1548 #5-9
vg3<-1686 #10-14
vg4<-1497 #15-19
vg5<-1459 #20-24
vg6<-1726 #25-29
vg7<-2165 #30-34
vg8<-1869 #35-39
vg9<-1777 #40-44
vg10=1874 #45-49
vg11=2398 #50-54
vg12=2446 #55-59
vg13=2253 #60-64
vg14=1852 #65-69
vg15=1750 #70-74
vg16=1275 #75-79
vg17=1152 #80-84
vg18=1054 #85+
xvg1<-0
xvg2<-0
xvg3<-0
xvg4<-0
xvg5<-0
xvg6<-0
xvg7<-10
xvg8<-10
xvg9<-10
xvg10<-0
xvg11<-0
xvg12<-0
xvg13<-0
xvg14<-0
xvg15<-0
xvg16<-0
xvg17<-0
xvg18=0
svg1<-vg1-xvg1
svg2<-vg2-xvg2
svg3<-vg3-xvg3
svg4<-vg4-xvg4
svg5<-vg5-xvg5
svg6<-vg6-xvg6
svg7<-vg7-xvg7
svg8<-vg8-xvg8
svg9<-vg9-xvg9
svg10<-vg10-xvg10
svg11<-vg11-xvg11
svg12<-vg12-xvg12
svg13<-vg13-xvg13
svg14<-vg14-xvg14
svg15<-vg15-xvg15
svg16<-vg16-xvg16
svg17<-vg17-xvg17
svg18=vg18-xvg18
xdvg1<-0
xdvg2<-0
xdvg3<-0
xdvg4<-0
xdvg5<-0
xdvg6<-0
xdvg7<-0
xdvg8<-0
xdvg9<-0
xdvg10<-0
xdvg11<-0
xdvg12<-0
xdvg13<-0
xdvg14<-0
xdvg15<-0
xdvg16<-0
xdvg17<-0
xdvg18=0
rvg1<-0
rvg2<-0
rvg3<-0
rvg4<-0
rvg5<-0
rvg6<-0
rvg7<-10
rvg8<-10
rvg9<-10
rvg10<-0
rvg11<-0
rvg12<-0
rvg13<-0
rvg14<-0
rvg15<-0
rvg16<-0
rvg17<-0
rvg18=0
päev = 0
indeks = 0

alfa = matrix(c(2,0.5,0.5,0.5,0.5,0.5,4,4,0.5,0.5,4,4,0.25,0.25,0.25,0,0,0,
                0.6,5,2,2,0.5,0.5,0.5,0.5,4,4,0.5,0.5,4,4,0.2,0.5,0,0,
                0.2,0.2,10,5,2,0.5,0.5,2,0.5,0.5,2,4,6,3,3,1,0,0,
                0.5,0.2,0.2,10,5,2,0.5,0.5,0.5,0.5,10,5,2,2,1,1,0.5,0.5,
                0,0.5,0.5,2,10,5,2,0.5,0.5,2,2,0.5,0.5,5,10,5,2,2,
                0,0.1,1,2,0.5,5,10,5,5,5,4,4,2,2,1,1,0.5,0,
                4,2,0.5,0.5,0.5,5,10,10,5,5,4,4,3,3,5,4,1,1,
                4,4,2,2,5,10,5,5,4,4,2,2,2,2,1,1,3,1,
                1,1,3,3,1,1,3,3,10,5,4,3,2,2,1,2,3,1,
                0.5,0.5,3,4,0.5,0.5,1,2,4,10,5,4,3,2,1,1,3,3,
                3,3,1,1,2,2,0.5,0.5,4,5,10,10,3,2,1,1,1,1,
                2,2,3,3,0.5,0.5,3,2,1,2,2,10,5,2,1,1,0.5,0.5,
                0.5,3,3,2,0.5,0.5,0.5,0.5,1,1,3,5,10,5,2,1,0,0.5,
                0.5,0.5,3,3,2,0.5,0.5,0.5,0.5,1,1,3,5,10,5,2,1,0.5,
                0.5,0.5,0.5,3,3,2,1,0.5,0.5,0.5,1,1,4,4,12,11,0.5,0.5,
                0.5,0.5,0.5,0.5,2,2,4,4,1,1,5,2,12,12,0.5,12,0.1,0.5,
                0.5,0.5,0.5,0.5,0.5,2,2,1,1,2,4,4,3,3,3,3,15,15,
                0.5,0.5,0.5,0.5,0.5,0.5,2,3,4,1,1,1,1,1,1,1,1,15
                ),nrow=18,byrow=T)

for(i in 1:nrow(alfa)){
  alfa[,i]=alfa[,i]*(1/(sum(alfa[,i])))
}

# rho <- sample(seq(from=0.01,to=0.55,by=0.01),18*18,replace=T)
# rho <- matrix(rho*0.1, nrow = 18)
rho <- rep(NA,18*18)
rho<-matrix(rho,nrow=18)

for(i in 1:18){
  for(j in 1:18){
    rho[i,j]=min(dnorm(j,mean=12,sd=3)+dnorm(j,mean=13,sd=2)+dnorm(i,mean=11,sd=i)+dnorm(j,mean=122,sd=j),1)
  }
}

rho = 0.6*rho

ck <- c(5,5,5,5,20,20,15,3,5,5,3,3,2,2,2,2,2,2)
sumhowmany=0
indeks=0
päev=0
df2 <- data.frame(päev,svg1,svg2,svg3,svg4,svg5,svg6,svg7,svg8,svg9,svg10,svg11,
                  svg12,svg13,svg14,svg15,svg16,svg17,svg18,
                  xvg1,xvg2,xvg3,xvg4,xvg5,xvg6,xvg7,xvg8,xvg9,
                  xvg10,xvg11,xvg12,xvg13,xvg14,xvg15,xvg16,xvg17,xvg18,
                  xdvg1,xdvg2,xdvg3,xdvg4,xdvg5,xdvg6,xdvg7,xdvg8,xdvg9,
                  xdvg10,xdvg11,xdvg12,xdvg13,xdvg14,xdvg15,xdvg16,xdvg17,xdvg18,
                  rvg1,rvg2,rvg3,rvg4,rvg5,rvg6,rvg7,rvg8,rvg9,rvg10,
                  rvg11,rvg12,rvg13,rvg14,rvg15,rvg16,rvg17,rvg18,indeks,sumhowmany)
df2 <- df2[-1,]

for(i in 1:1000){
# #rho = c(0.02,0.1,0.2)
  ti=1
  vg1<-1511 #0-4
  vg2<-1548 #5-9
  vg3<-1686 #10-14
  vg4<-1497 #15-19
  vg5<-1459 #20-24
  vg6<-1726 #25-29
  vg7<-2165 #30-34
  vg8<-1869 #35-39
  vg9<-1777 #40-44
  vg10=1874 #45-49
  vg11=2398 #50-54
  vg12=2446 #55-59
  vg13=2253 #60-64
  vg14=1852 #65-69
  vg15=1750 #70-74
  vg16=1275 #75-79
  vg17=1152 #80-84
  vg18=1054 #85+
  xvg1<-0
  xvg2<-0
  xvg3<-0
  xvg4<-0
  xvg5<-0
  xvg6<-0
  xvg7<-10
  xvg8<-10
  xvg9<-10
  xvg10<-0
  xvg11<-0
  xvg12<-0
  xvg13<-0
  xvg14<-0
  xvg15<-0
  xvg16<-0
  xvg17<-0
  xvg18=0
  svg1<-vg1-xvg1
  svg2<-vg2-xvg2
  svg3<-vg3-xvg3
  svg4<-vg4-xvg4
  svg5<-vg5-xvg5
  svg6<-vg6-xvg6
  svg7<-vg7-xvg7
  svg8<-vg8-xvg8
  svg9<-vg9-xvg9
  svg10<-vg10-xvg10
  svg11<-vg11-xvg11
  svg12<-vg12-xvg12
  svg13<-vg13-xvg13
  svg14<-vg14-xvg14
  svg15<-vg15-xvg15
  svg16<-vg16-xvg16
  svg17<-vg17-xvg17
  svg18=vg18-xvg18
  xdvg1<-0
  xdvg2<-0
  xdvg3<-0
  xdvg4<-0
  xdvg5<-0
  xdvg6<-0
  xdvg7<-0
  xdvg8<-0
  xdvg9<-0
  xdvg10<-0
  xdvg11<-0
  xdvg12<-0
  xdvg13<-0
  xdvg14<-0
  xdvg15<-0
  xdvg16<-0
  xdvg17<-0
  xdvg18=0
  rvg1<-0
  rvg2<-0
  rvg3<-0
  rvg4<-0
  rvg5<-0
  rvg6<-0
  rvg7<-10
  rvg8<-10
  rvg9<-10
  rvg10<-0
  rvg11<-0
  rvg12<-0
  rvg13<-0
  rvg14<-0
  rvg15<-0
  rvg16<-0
  rvg17<-0
  rvg18=0
  #c=2
  Tx1 = 5
  Tx2 = 3
  #rho=0.3

  number_added = 0
  number_taken = 0
  world <- c(svg1,svg2,svg3,svg4,svg5,svg6,svg7,svg8,svg9,svg10,svg11,svg12,
             svg13,svg14,svg15,svg16,svg17,svg18,
              xvg1,xvg2,xvg3,xvg4,xvg5,xvg6,xvg7,xvg8,xvg9,xvg10,xvg11,xvg12,
             xvg13,xvg14,xvg15,xvg16,xvg17,xvg18,
              xdvg1,xdvg2,xdvg3,xdvg4,xdvg5,xdvg6,xdvg7,xdvg8,xdvg9,xdvg10,
             xdvg11,xdvg12,xdvg13,xdvg14,xdvg15,xdvg16,xdvg17,xdvg18,
              rvg1,rvg2,rvg3,rvg4,rvg5,rvg6,rvg7,rvg8,rvg9,rvg10,rvg11,
             rvg12,rvg13,rvg14,rvg15,rvg16,rvg17,rvg18)
  n=sum(world)
  indeks = i
  päev=0
  päev=0
  plum = T
  sumhowmany=0
  how_set<-data.frame(xvg1,xvg2,xvg3,xvg4,xvg5,xvg6,xvg7,xvg8,xvg9,xvg10,xvg11,xvg12,
             xvg13,xvg14,xvg15,xvg16,xvg17,xvg18)
  päev = 0
  väärtused <- c(päev,svg1,svg2,svg3,svg4,svg5,svg6,svg7,svg8,svg9,svg10,svg11,svg12,
             svg13,svg14,svg15,svg16,svg17,svg18,
              xvg1,xvg2,xvg3,xvg4,xvg5,xvg6,xvg7,xvg8,xvg9,xvg10,xvg11,xvg12,
             xvg13,xvg14,xvg15,xvg16,xvg17,xvg18,
              xdvg1,xdvg2,xdvg3,xdvg4,xdvg5,xdvg6,xdvg7,xdvg8,xdvg9,xdvg10,
             xdvg11,xdvg12,xdvg13,xdvg14,xdvg15,xdvg16,xdvg17,xdvg18,
              rvg1,rvg2,rvg3,rvg4,rvg5,rvg6,rvg7,rvg8,rvg9,rvg10,rvg11,
             rvg12,rvg13,rvg14,rvg15,rvg16,rvg17,rvg18,indeks,sumhowmany)
  df2[nrow(df2)+1,]=väärtused
  if(i%%20==0){
    print(i)
  }
  while(plum){
    svg <- as.numeric(world[1:18])
    xvg <- as.numeric(world[19:36])
    xdvg <- as.numeric(world[37:54])
    rvg <-as.numeric(world[55:72])
    how_many_added <- rep(NA,length(svg))
    for(j in 1:length(svg)){
      how_many_added[j]=ifelse(nakatunude_arv(svg,xvg,xdvg,rvg,ck,j,alfa,rho)<svg[j],nakatunude_arv(svg,xvg,xdvg,rvg,ck,j,alfa,rho),svg[j])
    }
    sumhowmany <- sum(how_many_added)
    päev=päev + 1
    how_set[nrow(how_set)+1,] <- how_many_added
    if(sum(c(world[1:18],world[55:72]))==n){
      plum = F
      #print(paste("päev",päev))
      #print(c("S ", "X ", "R "))
      #print(world)
    }
    else{
      #print(paste("päev",päev))
      #print(c("S ", "X ", "R "))
      #print(world)
      world[19:36] = world[19:36]+how_many_added
      world[1:18] = world[1:18]-how_many_added
      if((Tx1-Tx2)<ti){
        #number_taken <- how_set[ti-Tx2+1,]
        world[19:36] = world[19:36]-as.numeric(how_set[ti-(Tx1-Tx2),])
        world[37:54] = world[37:54]+as.numeric(how_set[ti-(Tx1-Tx2),])
        if(Tx1<ti){
          world[37:54] = world[37:54]-as.numeric(how_set[ti-Tx1,])
          world[55:72] = world[55:72]+as.numeric(how_set[ti-Tx1,])
        }
      }
      ti = ti + 1
      #number_added <- how_many_added
      väärtused <- c(päev,world,indeks,sumhowmany)
      df2[nrow(df2)+1,]=väärtused
    }
  }
}

df2$xvg1. = df2$xvg1+df2$xdvg1
df2$xvg2. = df2$xvg2+df2$xdvg2
df2$xvg3. = df2$xvg3+df2$xdvg3
df2$xvg4. = df2$xvg4+df2$xdvg4
df2$xvg5. = df2$xvg5+df2$xdvg5
df2$xvg6. = df2$xvg6+df2$xdvg6
df2$xvg7. = df2$xvg7+df2$xdvg7
df2$xvg8. = df2$xvg8+df2$xdvg8
df2$xvg9. = df2$xvg9+df2$xdvg9
df2$xvg10. = df2$xvg10+df2$xdvg10
df2$xvg11. = df2$xvg11+df2$xdvg11
df2$xvg12. = df2$xvg12+df2$xdvg12
df2$xvg13. = df2$xvg13+df2$xdvg13
df2$xvg14. = df2$xvg14+df2$xdvg14
df2$xvg15. = df2$xvg15+df2$xdvg15
df2$xvg16. = df2$xvg16+df2$xdvg16
df2$xvg17. = df2$xvg17+df2$xdvg17
df2$xvg18. = df2$xvg18+df2$xdvg18

df2$xvg <- NA

for(i in 1:nrow(df2)){
  df2$xvg[i]<-sum(df2[i,76:93])
  if(i%%2500==0){
  print(i)
  }
}

library("ggplot2")

library("reshape2")

df2$how_many_added <- 0

df2$xvgnoninf <- NA 

for(i in 1:nrow(df2)){
  df2$xvgnoninf[i]=sum(df2[i,20:37])
  if(i%%10000==0){
    print(i)
  }
}

df2$svg<-NA

for(i in 1:nrow(df2)){
  df2$svg[i]=sum(df2[i,2:19])
}

df2$rvg =NA

for(i in 1:nrow(df2)){
  df2$rvg[i]=sum(df2[i,56:73])
}


#a <- with(df, tapply(value,päev,mean))

df <- melt(df2[,1:19], id.vars = 'päev', variable.name = 'grupid')

dfsvg <- aggregate(value ~ grupid + päev, data = df, FUN= "mean" )

ggplot(dfsvg, aes(päev, value))+
  geom_line(aes(color=grupid))
  


df <- melt(df2[,c(1,76:93)],id.vars = 'päev', variable.name = 'grupid')

dfxvg <- aggregate(value ~ grupid + päev, data = df, FUN= "mean" )

ggplot(dfxvg, aes(päev, value))+
  geom_line(aes(color=grupid))

df <- melt(df2[,c(1,56:73)],id.vars = 'päev', variable.name = 'grupid')

dfrvg <- aggregate(value ~ grupid + päev, data = df, FUN= "mean" )

ggplot(dfrvg, aes(päev, value))+
  geom_line(aes(color=grupid))

dfsvg <- melt(df2[,c(1,97)],id.vars='päev',variable.name='grupid')

dfsvgmean <- aggregate(value ~ grupid + päev, data = dfsvg, FUN="median")
dfsvgsd <- aggregate(value ~ grupid + päev, data = dfsvg, FUN = "sd")

ggplot(data = dfsvg, aes(x=päev, y=value))+
  geom_jitter(size=0.001,width =0.125,color = "aquamarine")+
  geom_errorbar(data=dfsvgsd,aes(ymax = dfsvgmean$value+1.645*dfsvgsd$value, ymin = dfsvgmean$value-1.645*dfsvgsd$value,color="red"))+
  geom_line(data = dfsvgmean, aes(x=päev, y = value, color = "darkred"))+
  xlab("päev")+
  ylab("rahvastik")+
  labs(colour= "")+
  scale_color_manual(values=c(red="red",black="black",navyblue="navyblue",aquamarine="aquamarine",darkred="darkred"),labels=c("90% usaldusintervall","nakatunud","tervenenud","nakatumata","keskmine"))+
  geom_jitter(data = dfxvg, size=0.001,width =0.125,color = "black",aes(x=päev+0.375,y=value))+
  geom_errorbar(data=dfxvgsd,aes(x=päev+0.375,ymax = dfxvgmean$value+1.645*dfxvgsd$value, ymin = dfxvgmean$value-1.645*dfxvgsd$value,color="red"))+
  geom_line(data = dfxvgmean, aes(x=päev+0.375,y=value,color = "darkred"))+
  geom_jitter(data=dfrvg,size=0.001,width =0.125,color = "navyblue", aes(x=päev-0.375,y=value))+
  geom_errorbar(data=dfrvgsd,aes(x=päev-0.375,ymax = dfrvgmean$value+1.645*dfrvgsd$value, ymin = dfrvgmean$value-1.645*dfrvgsd$value,color="red"))+
  geom_line(data = dfrvgmean, aes(x=päev-0.375, y=value, color = "darkred"))

######

dfxvg <- melt(df2[,c(1,94)],id.vars='päev',variable.name='grupid')

dfxvgmean <- aggregate(value ~ grupid + päev, data = dfxvg, FUN="median")
dfxvgsd <- aggregate(value ~ grupid + päev, data = dfxvg, FUN = "sd")

ggplot(data = dfxvg, aes(x=päev, y=value))+
  geom_jitter(size=0.001,width =0.25,color = "black")+
  geom_errorbar(data=dfxvgsd,aes(ymax = dfxvgmean$value+1.645*dfxvgsd$value, ymin = dfxvgmean$value-1.645*dfxvgsd$value,color="red"))+
  xlab("päev")+
  ylab("Nakatunud X")+
  labs(colour= "")+
  scale_color_manual(values=c(red="red"),labels="90% usaldusintervall")

######

dfrvg <- melt(df2[,c(1,98)],id.vars='päev',variable.name='grupid')

dfrvgmean <- aggregate(value ~ grupid + päev, data = dfrvg, FUN="median")
dfrvgsd <- aggregate(value ~ grupid + päev, data = dfrvg, FUN = "sd")

ggplot(data = dfrvg, aes(x=päev, y=value))+
  geom_jitter(size=0.001,width =0.25,color = "black")+
  geom_errorbar(data=dfrvgsd,aes(ymax = dfrvgmean$value+1.645*dfrvgsd$value, ymin = dfrvgmean$value-1.645*dfrvgsd$value,color="red"))+
  xlab("päev")+
  ylab("Tervenenud R")+
  labs(colour= "")+
  scale_color_manual(values=c(red="red"),labels="90% usaldusintervall")


```

```{r}
indeks=0
päev=0
sumhowmany=0

df3 <- data.frame(päev,svg1,svg2,svg3,svg4,svg5,svg6,svg7,svg8,svg9,svg10,svg11,
                  svg12,svg13,svg14,svg15,svg16,svg17,svg18,
                  xvg1,xvg2,xvg3,xvg4,xvg5,xvg6,xvg7,xvg8,xvg9,
                  xvg10,xvg11,xvg12,xvg13,xvg14,xvg15,xvg16,xvg17,xvg18,
                  xdvg1,xdvg2,xdvg3,xdvg4,xdvg5,xdvg6,xdvg7,xdvg8,xdvg9,
                  xdvg10,xdvg11,xdvg12,xdvg13,xdvg14,xdvg15,xdvg16,xdvg17,xdvg18,
                  rvg1,rvg2,rvg3,rvg4,rvg5,rvg6,rvg7,rvg8,rvg9,rvg10,
                  rvg11,rvg12,rvg13,rvg14,rvg15,rvg16,rvg17,rvg18,indeks,sumhowmany=0)
df3 <- df3[-1,]

for(i in 1:1000){
# #rho = c(0.02,0.1,0.2)
  ti=1
  vg1<-1511 #0-4
  vg2<-1548 #5-9
  vg3<-1686 #10-14
  vg4<-1497 #15-19
  vg5<-1459 #20-24
  vg6<-1726 #25-29
  vg7<-2165 #30-34
  vg8<-1869 #35-39
  vg9<-1777 #40-44
  vg10=1874 #45-49
  vg11=2398 #50-54
  vg12=2446 #55-59
  vg13=2253 #60-64
  vg14=1852 #65-69
  vg15=1750 #70-74
  vg16=1275 #75-79
  vg17=1152 #80-84
  vg18=1054 #85+
  xvg1<-0
  xvg2<-0
  xvg3<-0
  xvg4<-0
  xvg5<-0
  xvg6<-0
  xvg7<-10
  xvg8<-10
  xvg9<-10
  xvg10<-0
  xvg11<-0
  xvg12<-0
  xvg13<-0
  xvg14<-0
  xvg15<-0
  xvg16<-0
  xvg17<-0
  xvg18=0
  svg1<-vg1-xvg1
  svg2<-vg2-xvg2
  svg3<-vg3-xvg3
  svg4<-vg4-xvg4
  svg5<-vg5-xvg5
  svg6<-vg6-xvg6
  svg7<-vg7-xvg7
  svg8<-vg8-xvg8
  svg9<-vg9-xvg9
  svg10<-vg10-xvg10
  svg11<-vg11-xvg11
  svg12<-vg12-xvg12
  svg13<-vg13-xvg13
  svg14<-vg14-xvg14
  svg15<-vg15-xvg15
  svg16<-vg16-xvg16
  svg17<-vg17-xvg17
  svg18=vg18-xvg18
  xdvg1<-0
  xdvg2<-0
  xdvg3<-0
  xdvg4<-0
  xdvg5<-0
  xdvg6<-0
  xdvg7<-0
  xdvg8<-0
  xdvg9<-0
  xdvg10<-0
  xdvg11<-0
  xdvg12<-0
  xdvg13<-0
  xdvg14<-0
  xdvg15<-0
  xdvg16<-0
  xdvg17<-0
  xdvg18=0
  rvg1<-0
  rvg2<-0
  rvg3<-0
  rvg4<-0
  rvg5<-0
  rvg6<-0
  rvg7<-10
  rvg8<-10
  rvg9<-10
  rvg10<-0
  rvg11<-0
  rvg12<-0
  rvg13<-0
  rvg14<-0
  rvg15<-0
  rvg16<-0
  rvg17<-0
  rvg18=0
  #c=2
  Tx1 = 5
  Tx2 = 3
  #rho=0.3

  number_added = 0
  number_taken = 0
  world <- c(svg1,svg2,svg3,svg4,svg5,svg6,svg7,svg8,svg9,svg10,svg11,svg12,
             svg13,svg14,svg15,svg16,svg17,svg18,
              xvg1,xvg2,xvg3,xvg4,xvg5,xvg6,xvg7,xvg8,xvg9,xvg10,xvg11,xvg12,
             xvg13,xvg14,xvg15,xvg16,xvg17,xvg18,
              xdvg1,xdvg2,xdvg3,xdvg4,xdvg5,xdvg6,xdvg7,xdvg8,xdvg9,xdvg10,
             xdvg11,xdvg12,xdvg13,xdvg14,xdvg15,xdvg16,xdvg17,xdvg18,
              rvg1,rvg2,rvg3,rvg4,rvg5,rvg6,rvg7,rvg8,rvg9,rvg10,rvg11,
             rvg12,rvg13,rvg14,rvg15,rvg16,rvg17,rvg18)
  n=sum(world)
  indeks = i
  päev=0
  päev=0
  plum = T
  how_set<-data.frame(xvg1,xvg2,xvg3,xvg4,xvg5,xvg6,xvg7,xvg8,xvg9,xvg10,xvg11,xvg12,
             xvg13,xvg14,xvg15,xvg16,xvg17,xvg18)
  päev = 0
  väärtused <- c(päev,svg1,svg2,svg3,svg4,svg5,svg6,svg7,svg8,svg9,svg10,svg11,svg12,
             svg13,svg14,svg15,svg16,svg17,svg18,
              xvg1,xvg2,xvg3,xvg4,xvg5,xvg6,xvg7,xvg8,xvg9,xvg10,xvg11,xvg12,
             xvg13,xvg14,xvg15,xvg16,xvg17,xvg18,
              xdvg1,xdvg2,xdvg3,xdvg4,xdvg5,xdvg6,xdvg7,xdvg8,xdvg9,xdvg10,
             xdvg11,xdvg12,xdvg13,xdvg14,xdvg15,xdvg16,xdvg17,xdvg18,
              rvg1,rvg2,rvg3,rvg4,rvg5,rvg6,rvg7,rvg8,rvg9,rvg10,rvg11,
             rvg12,rvg13,rvg14,rvg15,rvg16,rvg17,rvg18,indeks,sumhowmany)
  df3[nrow(df3)+1,]=väärtused
  if(i%%50==0){
    print(i)
  }
  while(plum){
    svg <- as.numeric(world[1:18])
    xvg <- as.numeric(world[19:36])
    xdvg <- as.numeric(world[37:54])
    rvg <-as.numeric(world[55:72])
    how_many_added <- rep(NA,length(svg))
    for(j in 1:length(svg)){
      how_many_added[j]=ifelse(nakatunude_arv2(svg,xvg,xdvg,rvg,ck,j,alfa,rho)<svg[j],nakatunude_arv2(svg,xvg,xdvg,rvg,ck,j,alfa,rho),svg[j])
    }
    sumhowmany = sum(how_many_added)
    päev=päev + 1
    how_set[nrow(how_set)+1,] <- how_many_added
    if(sum(c(world[1:18],world[55:72]))==n){
      plum = F
      #print(paste("päev",päev))
      #print(c("S ", "X ", "R "))
      #print(world)
    }
    else{
      #print(paste("päev",päev))
      #print(c("S ", "X ", "R "))
      #print(world)
      world[19:36] = world[19:36]+how_many_added
      world[1:18] = world[1:18]-how_many_added
      if((Tx1-Tx2)<ti){
        #number_taken <- how_set[ti-Tx2+1,]
        world[19:36] = world[19:36]-as.numeric(how_set[ti-(Tx1-Tx2),])
        world[37:54] = world[37:54]+as.numeric(how_set[ti-(Tx1-Tx2),])
        if(Tx1<ti){
          world[37:54] = world[37:54]-as.numeric(how_set[ti-Tx1,])
          world[55:72] = world[55:72]+as.numeric(how_set[ti-Tx1,])
        }
      }
      ti = ti + 1
      #number_added <- how_many_added
      väärtused <- c(päev,world,indeks,sumhowmany)
      df3[nrow(df3)+1,]=väärtused
    }
  }
}


df3$xvg1. = df3$xvg1+df3$xdvg1
df3$xvg2. = df3$xvg2+df3$xdvg2
df3$xvg3. = df3$xvg3+df3$xdvg3
df3$xvg4. = df3$xvg4+df3$xdvg4
df3$xvg5. = df3$xvg5+df3$xdvg5
df3$xvg6. = df3$xvg6+df3$xdvg6
df3$xvg7. = df3$xvg7+df3$xdvg7
df3$xvg8. = df3$xvg8+df3$xdvg8
df3$xvg9. = df3$xvg9+df3$xdvg9
df3$xvg10. = df3$xvg10+df3$xdvg10
df3$xvg11. = df3$xvg11+df3$xdvg11
df3$xvg12. = df3$xvg12+df3$xdvg12
df3$xvg13. = df3$xvg13+df3$xdvg13
df3$xvg14. = df3$xvg14+df3$xdvg14
df3$xvg15. = df3$xvg15+df3$xdvg15
df3$xvg16. = df3$xvg16+df3$xdvg16
df3$xvg17. = df3$xvg17+df3$xdvg17
df3$xvg18. = df3$xvg18+df3$xdvg18

df3$xvg <- NA

for(i in 1:nrow(df3)){
  df3$xvg[i]<-sum(df3[i,76:93])
  if(i%%2500==0){
  print(i)
  }
}

library("ggplot2")

library("reshape2")

df3$how_many_added <- 0

df3$xvgnoninf <- NA 

for(i in 1:nrow(df3)){
  df3$xvgnoninf[i]=sum(df3[i,20:37])
  if(i%%10000==0){
    print(i)
  }
}

df3$svg<-NA

for(i in 1:nrow(df3)){
  df3$svg[i]=sum(df3[i,2:19])
}

df3$rvg =NA

for(i in 1:nrow(df3)){
  df3$rvg[i]=sum(df3[i,56:73])
}


#a <- with(df, tapply(value,päev,mean))

df <- melt(df3[,1:19], id.vars = 'päev', variable.name = 'grupid')

dfsvg <- aggregate(value ~ grupid + päev, data = df, FUN= "mean" )

ggplot(dfsvg, aes(päev, value))+
  geom_line(aes(color=grupid))+
  xlim(0,65)
  


df <- melt(df3[,c(1,76:93)],id.vars = 'päev', variable.name = 'grupid')

dfxvg <- aggregate(value ~ grupid + päev, data = df, FUN= "mean" )

ggplot(dfxvg, aes(päev, value))+
  geom_line(aes(color=grupid))+
  xlim(0,65)

df <- melt(df3[,c(1,56:73)],id.vars = 'päev', variable.name = 'grupid')

dfrvg <- aggregate(value ~ grupid + päev, data = df, FUN= "mean" )

ggplot(dfrvg, aes(päev, value))+
  geom_line(aes(color=grupid))+
  xlim(0,65)

dfsvg <- melt(df3[,c(1,97)],id.vars='päev',variable.name='grupid')

dfsvgmean <- aggregate(value ~ grupid + päev, data = dfsvg, FUN="median")
dfsvgsd <- aggregate(value ~ grupid + päev, data = dfsvg, FUN = "sd")

ggplot(data = dfsvg, aes(x=päev, y=value))+
  geom_jitter(size=0.001,width =0.125,color = "aquamarine")+
  geom_errorbar(data=dfsvgsd,aes(ymax = dfsvgmean$value+1.645*dfsvgsd$value, ymin = dfsvgmean$value-1.645*dfsvgsd$value,color="red"))+
  geom_line(data = dfsvgmean, aes(x=päev, y = value, color = "darkred"))+
  xlab("päev")+
  ylab("rahvastik")+
  labs(colour= "")+
  scale_color_manual(values=c(red="red",black="black",navyblue="navyblue",aquamarine="aquamarine",darkred="darkred"),labels=c("90% usaldusintervall","nakatunud","tervenenud","nakatumata","keskmine"))+
  geom_jitter(data = dfxvg, size=0.001,width =0.125,color = "black",aes(x=päev+0.375,y=value))+
  geom_errorbar(data=dfxvgsd,aes(x=päev+0.375,ymax = dfxvgmean$value+1.645*dfxvgsd$value, ymin = dfxvgmean$value-1.645*dfxvgsd$value,color="red"))+
  geom_line(data = dfxvgmean, aes(x=päev+0.375,y=value,color = "darkred"))+
  geom_jitter(data=dfrvg,size=0.001,width =0.125,color = "navyblue", aes(x=päev-0.375,y=value))+
  geom_errorbar(data=dfrvgsd,aes(x=päev-0.375,ymax = dfrvgmean$value+1.645*dfrvgsd$value, ymin = dfrvgmean$value-1.645*dfrvgsd$value,color="red"))+
  geom_line(data = dfrvgmean, aes(x=päev-0.375, y=value, color = "darkred"))+
  xlim(0,62)

######

dfxvg <- melt(df3[,c(1,94)],id.vars='päev',variable.name='grupid')

dfxvgmean <- aggregate(value ~ grupid + päev, data = dfxvg, FUN="median")
dfxvgsd <- aggregate(value ~ grupid + päev, data = dfxvg, FUN = "sd")

ggplot(data = dfxvg, aes(x=päev, y=value))+
  geom_jitter(size=0.001,width =0.25,color = "black")+
  geom_errorbar(data=dfxvgsd,aes(ymax = dfxvgmean$value+1.645*dfxvgsd$value, ymin = dfxvgmean$value-1.645*dfxvgsd$value,color="red"))+
  xlab("päev")+
  ylab("Nakatunud X")+
  labs(colour= "")+
  scale_color_manual(values=c(red="red"),labels="90% usaldusintervall")

######

dfrvg <- melt(df3[,c(1,98)],id.vars='päev',variable.name='grupid')

dfrvgmean <- aggregate(value ~ grupid + päev, data = dfrvg, FUN="median")
dfrvgsd <- aggregate(value ~ grupid + päev, data = dfrvg, FUN = "sd")

ggplot(data = dfrvg, aes(x=päev, y=value))+
  geom_jitter(size=0.001,width =0.25,color = "black")+
  geom_errorbar(data=dfrvgsd,aes(ymax = dfrvgmean$value+1.645*dfrvgsd$value, ymin = dfrvgmean$value-1.645*dfrvgsd$value,color="red"))+
  xlab("päev")+
  ylab("Tervenenud R")+
  labs(colour= "")+
  scale_color_manual(values=c(red="red"),labels="90% usaldusintervall")

ESn <- round(with(df2, tapply(svg,päev,mean)))

EXn <- round(with(df2, tapply(xvg,päev,mean)))

ERn <- round(with(df2, tapply(rvg,päev,mean)))

ESn2 <- round(with(df3, tapply(svg,päev,mean)))

EXn2 <- round(with(df3, tapply(xvg,päev,mean)))

ERn2 <- round(with(df3, tapply(rvg,päev,mean)))

sSn <- with(df2, tapply(svg,päev,sd))

sXn <- with(df2, tapply(xvg, päev, sd))

sRn <- with(df2, tapply(rvg, päev, sd))

sSn2 <- with(df3, tapply(svg,päev,sd))

sXn2 <- with(df3,tapply(xvg,päev,sd))

sRn2 <- with(df3,tapply(rvg,päev,sd))

ESn <- round(with(df2, tapply(svg,päev,mean)))

EXn <- round(with(df2, tapply(xvg,päev,mean)))

ERn <- round(with(df2, tapply(rvg,päev,mean)))

ESn2 <- round(with(df3, tapply(svg,päev,mean)))

EXn2 <- round(with(df3, tapply(xvg,päev,mean)))

ERn2 <- round(with(df3, tapply(rvg,päev,mean)))

päev = length(ESn)

tulem <- data.frame(päev,ESn,EXn,ERn,)

ESn <- c()

EXn <- c()

ERn <- c()

sSn <- c()

sXn <- c()

sRn <- c()

qSnu <- c()

qXnu <- c()

qRnu <- c()

qSnl <- c()

qXnl <- c()

qRnl <- c()

for(i in 1:length(unique(df2$päev))){
  ESn <- c(ESn, mean(df2$svg[df2$päev==unique(df2$päev)[i]]))
  EXn <- c(EXn, mean(df2$xvg[df2$päev==unique(df2$päev)[i]]))
  ERn <- c(ERn, mean(df2$xvg[df2$päev==unique(df2$päev)[i]]))
  sSn <- c(sSn, sd(df2$svg[df2$päev==unique(df2$päev)[i]]))
  sXn <- c(sXn, sd(df2$xvg[df2$päev==unique(df2$päev)[i]]))
  sRn <- c(sRn, sd(df2$rvg[df2$päev==unique(df2$päev)[i]]))
  qSnu <- c(qSnu, mean(df2$svg[df2$päev==unique(df2$päev)[i]])+1.645*sd(df2$svg[df2$päev==unique(df2$päev)[i]]))
  qXnu <- c(qXnu, mean(df2$xvg[df2$päev==unique(df2$päev)[i]])+1.645*sd(df2$xvg[df2$päev==unique(df2$päev)[i]]))
  qRnu <- c(qRnu, mean(df2$rvg[df2$päev==unique(df2$päev)[i]])+1.645*sd(df2$rvg[df2$päev==unique(df2$päev)[i]]))
  qSnl <- c(qSnl, mean(df2$svg[df2$päev==unique(df2$päev)[i]])-1.645*sd(df2$svg[df2$päev==unique(df2$päev)[i]]))
  qXnl <- c(qXnl, mean(df2$xvg[df2$päev==unique(df2$päev)[i]])-1.645*sd(df2$xvg[df2$päev==unique(df2$päev)[i]]))
  qRnl <- c(qRnl, mean(df2$rvg[df2$päev==unique(df2$päev)[i]])-1.645*sd(df2$rvg[df2$päev==unique(df2$päev)[i]]))
  print(i)
}

tulem <- round(data.frame(päev=unique(df2$päev),EXn, sXn, qXnu, qXnl))

kESn <- c()

kEXn <- c()

kERn <- c()

ksSn <- c()

ksXn <- c()

ksRn <- c()

kqSnu <- c()

kqXnu <- c()

kqRnu <- c()

kqSnl <- c()

kqXnl <- c()

kqRnl <- c()

for(i in 1:length(unique(df3$päev))){
  kESn <- c(kESn, mean(df3$svg[df3$päev==unique(df3$päev)[i]]))
  kEXn <- c(kEXn, mean(df3$xvg[df3$päev==unique(df3$päev)[i]]))
  kERn <- c(kERn, mean(df3$xvg[df3$päev==unique(df3$päev)[i]]))
  ksSn <- c(ksSn, sd(df3$svg[df3$päev==unique(df3$päev)[i]]))
  ksXn <- c(ksXn, sd(df3$xvg[df3$päev==unique(df3$päev)[i]]))
  ksRn <- c(ksRn, sd(df3$rvg[df3$päev==unique(df3$päev)[i]]))
  kqSnu <- c(kqSnu, mean(df3$svg[df3$päev==unique(df3$päev)[i]])+1.645*sd(df3$svg[df3$päev==unique(df3$päev)[i]]))
  kqXnu <- c(kqXnu, mean(df3$xvg[df3$päev==unique(df3$päev)[i]])+1.645*sd(df3$xvg[df3$päev==unique(df3$päev)[i]]))
  kqRnu <- c(kqRnu, mean(df3$rvg[df3$päev==unique(df3$päev)[i]])+1.645*sd(df3$rvg[df3$päev==unique(df3$päev)[i]]))
  kqSnl <- c(kqSnl, mean(df3$svg[df3$päev==unique(df3$päev)[i]])-1.645*sd(df3$svg[df3$päev==unique(df3$päev)[i]]))
  kqXnl <- c(kqXnl, mean(df3$xvg[df3$päev==unique(df3$päev)[i]])-1.645*sd(df3$xvg[df3$päev==unique(df3$päev)[i]]))
  kqRnl <- c(kqRnl, mean(df3$rvg[df3$päev==unique(df3$päev)[i]])-1.645*sd(df3$rvg[df3$päev==unique(df3$päev)[i]]))
  print(i)
}

tulem2 <- round(data.frame(päev=unique(df3$päev),kEXn, ksXn, kqXnu, kqXnl))

tulem3 <- left_join(tulem,tulem2,by="päev")


```

```{r}
alfa2
```